---
title: "SISBID Module 1"
output:
  html_document:
    theme: cosmo
  pdf_document: default
---

## Data Wrangling with R

**Instructors:** `r config::get("instructors")`

**Class Schedule:**

* M/T: 8am-2:30pm PST, W: 8am-11am PST

* Location: Zoom (see class email or Slack for link)

**Software:**

Please install the latest versions of R and RStudio:
https://sisbid.github.io/Data-Wrangling/00_Setup/Setup.html

<!--
**Resources:**

* [Rstudio Cloud Class Project Homepage](https://rstudio.cloud/spaces/21228/projects)
* [Rstudio's cheatsheets](http://www.rstudio.com/resources/cheatsheets/) 
* [R for Data Science](http://r4ds.had.co.nz/)
* [JHU Cloud-Based Data Science](https://leanpub.com/universities/set/jhu/cloud-based-data-science)
* [Git for Humans](https://speakerdeck.com/alicebartlett/git-for-humans)
* [GitHub Labs](https://lab.github.com/)
* [swirl](http://swirlstats.com/)
* [Datacamp](http://datacamp.com/)

--> 

**Schedule**

|             | **Lecture**                                               | **Lab**               | **Lab Key**                          |
|-------------|-----------------------------------------------------------|-----------------------|--------------------------------------|
| **Day 0**   |                                                           |                       |                                      |
|             | [Setup][01] ([PDF][02])                                   |                       |                                      |
| **Day 1**   |                                                           |                       |                                      |
| 8:00-8:50   | [Introduction][03] ([PDF][04])                            |                       |                                      |
| 8:50-9:05   | Break                                                     |                       |                                      |
| 9:05-9:55   | [Reproducible Research & Github][05] ([PDF][06])          | [lab][07]             | [lab key][08] / [lab key output][09] |
| 9:55-10:10  | Break                                                     |                       |                                      |
| 10:10-11:00 | [Data Input/Output Part 1][10] ([PDF][11]/[Rmd][12])      | [lab][13]             | [lab key][14] / [lab key output][15] |
| 11:00-11:30 | Break                                                     |                       |                                      |
| 11:30-12:20 | [Data Input/Output Part 2][16] ([PDF][17])/[Rmd][18])     | [lab][19]             | [lab key][20] / [lab key output][21] |
| 12:20-12:35 | Break                                                     |                       |                                      |
| 12:35-1:25  | [Data Subsetting Part 1][22] ([PDF][23]/[Rmd][24])        | [lab][25]             | [lab key][26] / [lab key output][27] |
| 1:25-1:40   | Break                                                     |                       |                                      |
| 1:40-2:30   | [Data Subsetting Part 2][28] ([PDF][29]/[Rmd][30])        | [lab][31]             | [lab key][32] / [lab key output][33] |
| **Day 2**   |                                                           |                       |                                      |
| 8:00-8:50   | [Missing Data][34] ([PDF][35]/[Rmd][36])                  | [lab][37]             | [lab key][38] / [lab key output][39] |
| 8:50-9:05   | Break                                                     |                       |                                      |
| 9:05-9:55   | [Data Summarization][40] ([PDF][41]/[Rmd][42])            | [lab][43]             | [lab key][44] / [lab key output][45] |
| 9:55-10:10  | Break                                                     |                       |                                      |
| 10:10-11:00 | [Data Cleaning Part 1][46] ([PDF][47]/[Rmd][48])          | [lab][49]             | [lab key][50] / [lab key output][51] |
| 11:00-11:30 | Break                                                     |                       |                                      |
| 11:30-12:20 | [Data Cleaning Part 2][52] ([PDF][53]/[Rmd][54])          | [lab][55]             | [lab key][56] / [lab key output][57] |
| 12:20-12:35 | Break                                                     |                       |                                      |
| 12:35-1:25  | [Data Reshaping][58] ([PDF][59]/[Rmd][60])                | [lab][61]             | [lab key][62] / [lab key output][63] |
| 1:25-1:40   | Break                                                     |                       |                                      |
| 1:40-2:30   | [Data Merging and Joining][64] ([PDF][65]/[Rmd][66])      | [lab][67]             | [lab key][68] / [lab key output][69] |
| **Day 3**   |                                                           |                       |                                      |
| 8:00-8:50   | [Factors][70] ([PDF][71]/[Rmd][72])                       | [lab][73]             | [lab key][74] / [lab key output][75] |
| 8:50-9:05   | Break                                                     |                       |                                      |
| 9:05-9:55   | [Functional Programming Part 1][76] ([PDF][77]/[Rmd][78]) | [lab][79]             | [lab key][80] / [lab key output][81] |
| 9:55-10:10  | Break                                                     |                       |                                      |
| 10:10-11:00 | [Functional Programming Part 2][82] ([PDF][83]/[Rmd][84]) | [lab][85]             | [lab key][86] / [lab key output][87] |
|             | [Wrap Up][88] ([PDF][89])                                 |                       |                                      |

[01]: 00_Setup/Setup.html  
[02]: 00_Setup/Setup.pdf  

[03]: https://docs.google.com/presentation/d/1JIcyI7Yofu5KeTHU4_NrYIrIzSwHuiu1iK_87v4aNmY/edit?usp=drive_link  
[04]: 01_Introduction/sisbid_intro_2026.pdf  

[05]: https://docs.google.com/presentation/d/1MwzHvoYqPdbVAe-Ci1F3ZGmf6GumWlA3GDILuHYJx20/edit?usp=drive_link
[06]: 02_Reproducible_Research/sisbid_rep_research_and_github_2026.pdf  
[07]: 02_Reproducible_Research/lab/rmarkdown-lab.Rmd  
[08]: 02_Reproducible_Research/lab/rmarkdown-lab-key.Rmd  
[09]: 02_Reproducible_Research/lab/rmarkdown-lab-key.html  

[10]: 03_Data_IO/Data_IO_Part1.html  
[11]: 03_Data_IO/Data_IO_Part1.pdf  
[12]: 03_Data_IO/Data_IO_Part1.Rmd  
[13]: 03_Data_IO/lab/data-io-lab-part1.Rmd  
[14]: 03_Data_IO/lab/data-io-lab-part1-key.Rmd  
[15]: 03_Data_IO/lab/data-io-lab-part1-key.html  

[16]: 03_Data_IO/Data_IO_Part2.html  
[17]: 03_Data_IO/Data_IO_Part2.pdf  
[18]: 03_Data_IO/Data_IO_Part2.Rmd  
[19]: 03_Data_IO/lab/data-io-lab-part2.Rmd  
[20]: 03_Data_IO/lab/data-io-lab-part2-key.Rmd  
[21]: 03_Data_IO/lab/data-io-lab-part2-key.html  

[22]: 05_Data_Subsetting/Data_Subsetting_Part1.html  
[23]: 05_Data_Subsetting/Data_Subsetting_Part1.pdf  
[24]: 05_Data_Subsetting/Data_Subsetting_Part1.Rmd  
[25]: 05_Data_Subsetting/lab/data-subsetting-lab-part1.Rmd  
[26]: 05_Data_Subsetting/lab/data-subsetting-lab-part1-key.Rmd  
[27]: 05_Data_Subsetting/lab/data-subsetting-lab-part1-key.html  

[28]: 05_Data_Subsetting/Data_Subsetting_Part2.html  
[29]: 05_Data_Subsetting/Data_Subsetting_Part2.pdf  
[30]: 05_Data_Subsetting/Data_Subsetting_Part2.Rmd  
[31]: 05_Data_Subsetting/lab/data-subsetting-lab-part2.Rmd  
[32]: 05_Data_Subsetting/lab/data-subsetting-lab-part2-key.Rmd  
[33]: 05_Data_Subsetting/lab/data-subsetting-lab-part2-key.html  

[34]: 07_Missing_Data/Data_Missing.html  
[35]: 07_Missing_Data/Data_Missing.pdf  
[36]: 07_Missing_Data/Data_Missing.Rmd  
[37]: 07_Missing_Data/lab/missing-data-lab.Rmd  
[38]: 07_Missing_Data/lab/missing-data-lab-key.Rmd  
[39]: 07_Missing_Data/lab/missing-data-lab-key.html  

[40]: 08_Data_Summarization/Data_Summarization.html  
[41]: 08_Data_Summarization/Data_Summarization.pdf  
[42]: 08_Data_Summarization/Data_Summarization.Rmd  
[43]: 08_Data_Summarization/lab/data-summarization-lab.Rmd  
[44]: 08_Data_Summarization/lab/data-summarization-lab-key.Rmd  
[45]: 08_Data_Summarization/lab/data-summarization-lab-key.html  

[46]: 09_Data_Cleaning/Data_Cleaning_Part1.html  
[47]: 09_Data_Cleaning/Data_Cleaning_Part1.pdf  
[48]: 09_Data_Cleaning/Data_Cleaning_Part1.Rmd  
[49]: 09_Data_Cleaning/lab/data-cleaning-lab.Rmd  
[50]: 09_Data_Cleaning/lab/data-cleaning-lab-key.Rmd  
[51]: 09_Data_Cleaning/lab/data-cleaning-lab-key.html  

[52]: 09_Data_Cleaning/Data_Cleaning_Part2.html  
[53]: 09_Data_Cleaning/Data_Cleaning_Part2.pdf  
[54]: 09_Data_Cleaning/Data_Cleaning_Part2.Rmd  
[55]: 09_Data_Cleaning/lab/data-cleaning-lab-part2.Rmd  
[56]: 09_Data_Cleaning/lab/data-cleaning-lab-part2-key.Rmd  
[57]: 09_Data_Cleaning/lab/data-cleaning-lab-part2-key.html  

[58]: 11_Data_Reshaping/Data_Reshaping.html  
[59]: 11_Data_Reshaping/Data_Reshaping.pdf  
[60]: 11_Data_Reshaping/Data_Reshaping.Rmd  
[61]: 11_Data_Reshaping/lab/data-reshaping-lab.Rmd  
[62]: 11_Data_Reshaping/lab/data-reshaping-lab-key.Rmd  
[63]: 11_Data_Reshaping/lab/data-reshaping-lab-key.html  

[64]: 12_Data_Merging/Merging_Join.html  
[65]: 12_Data_Merging/Merging_Join.pdf  
[66]: 12_Data_Merging/Merging_Join.Rmd  
[67]: 12_Data_Merging/lab/merging-lab.Rmd  
[68]: 12_Data_Merging/lab/merging-lab-key.Rmd  
[69]: 12_Data_Merging/lab/merging-lab-key.html  

[70]: 13_Factors/Factors.html  
[71]: 13_Factors/Factors.pdf  
[72]: 13_Factors/Factors.Rmd  
[73]: 13_Factors/lab/factors-lab.Rmd  
[74]: 13_Factors/lab/factors-lab-key.Rmd  
[75]: 13_Factors/lab/factors-lab-key.html  

[76]: 14_Functional_Programming/Functional_Programming.html  
[77]: 14_Functional_Programming/Functional_Programming.pdf  
[78]: 14_Functional_Programming/Functional_Programming.Rmd  
[79]: 14_Functional_Programming/lab/functional-program-lab.Rmd  
[80]: 14_Functional_Programming/lab/functional-program-lab-key.Rmd  
[81]: 14_Functional_Programming/lab/functional-program-lab-key.html  

[82]: 14_Functional_Programming/Functional_Programming.html  
[83]: 14_Functional_Programming/Functional_Programming.pdf  
[84]: 14_Functional_Programming/Functional_Programming.Rmd  
[85]: 14_Functional_Programming/lab/functional-program-lab.Rmd  
[86]: 14_Functional_Programming/lab/functional-program-lab-key.Rmd  
[87]: 14_Functional_Programming/lab/functional-program-lab-key.html  

[88]: https://docs.google.com/presentation/d/17Ice9AFi_y7XH41CnkCyaODDTgWFNxryI3AofXwY7c0/edit?usp=drive_link
[89]: 16_Wrap_Up/sisbid_wrap_up_2026.pdf  


**Miscellaneous**

Feel free to submit typos/errors/etc via the github repository associated with the class: 
https://github.com/SISBID/Data-Wrangling

```{r, eval = FALSE, echo = FALSE}
## Render this file:
rmarkdown::render('index.Rmd')
```

This page was last updated on `r Sys.time()` Eastern Time.
