---
title: "subsetting Lab"
author: "Andrew Jaffe"
date: "July 11, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this lab you can use the interactive console to explore but please record your commands here.  

Remember anything you type here can be "sent" to the console with: Cmd-Enter (OS-X) or Ctrl-Enter (Windows/Linux).

1. Check to see if you have the `mtcars` dataset (which is included in the `datasets` package)

2. What class is `mtcars`?

3. How many observations (rows) and variables (columns) are in the `mtcars` dataset?

4. Select the subset of rows that get more than 20 miles per gallon (mpg) of fuel efficiency - how many are there?

5. Select the subset of rows that get less than 16 miles per gallon (mpg) of fuel efficiency and have more than 100 horsepower (hp) - how many are there?

6. Create a subset of the data that only contains the columns:wt, qsec, and hp for only the cars that have 8 cylinder, and assign this object to `carsSub` - what are the dimensions of this dataset?

7. Convert the column names of `carsSub` to all upper case

8. Re-order the rows of `carsSub` by weight in increasing order

9. Copy mtcars into a variable called `cars` and rename the `mpg` column in `cars` to `MPG`

10. Subset the columns from mtcars that end in "p" and call the new data frame `pvars`

